name: Blink-Worker CD

# develop 브랜치 push 시
on:
  push:
    branches: [ feat/fcm-push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # JDK 세팅
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      #gradle 캐싱
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # application.yml을 s3로 부터 다운로드
      - name: Getting S3 Object
        id: s3
        uses: jcfrane/s3-get-object-action@v1.0
        with:
          region: ap-southeast-2
          bucket: blink-env
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          object-key: env/dev/application.yml
          filename: application.yml

      # move application yml
      - name: Move application.yml
        run: |
          mkdir -p src/main/resources
          mv application.yml src/main/resources

      # gradlew 권한
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      # 테스트를 제외한 프로젝트 빌드
      - name: Build With Gradle
        run: |
          ls -al .
          ls -al ./src
          ls -al ./src/main
          ls -al ./src/main/resources 
          ./gradlew build -x test

      # version 라벨링용
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00" # 한국 시간

      # 배포용
      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp build/libs/*-SNAPSHOT.jar deploy/application.jar
          if test -e Procfile ; then cp Procfile ./deploy/Procfile ; fi
          if test -d .ebextensions ; then cp -r .ebextensions deploy/.ebextensions ; fi
          if test -d .platform ; then cp -r .platform deploy/.platform ; fi
          if test -e cron.yaml ; then cp cron.yaml deploy/cron.yaml ; fi
          ls -al deploy
          cd deploy && zip -r deploy.zip .

        # Beanstalk Deploy 플러그인 사용
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: link-server-worker
          environment_name: Link-server-worker-env-1
          version_label: Link-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip
          wait_for_environment_recovery: 900